#! /bin/sh
# chkconfig: 2345 90 10
# description: start GetSubCode sevice
RETVAL=0
export DIR_HOME=/data/subcode
start()
{
        if [ -f $DIR_HOME/start.sh ];
          then
            echo $"Starting GetSubCode"
                cd $DIR_HOME
                ./start.sh
            RETVAL=$?
            echo " OK"
            return $RETVAL
        fi
}
stop()
{
        
    echo $"Stopping GetSubCode"
    RETVAL=$?
    ps -fwwu root | grep getSubCode.py | grep -v grep | grep -v PID | awk '{print $2}'|xargs kill -9
    echo " OK"
    # [ $RETVAL -eq 0 ] && rm -f /var/lock/...
    return $RETVAL
        
}
 
case "$1" in
 start) 
        start
        ;;
 stop)  
        stop
        ;;
                                                
 restart)
         echo $"Restaring GetSubCode"
         $0 stop
         sleep 2
         $0 start
         ;;
 *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
exit $RETVAL
